# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Build
  branches:
    include:
    - 20*
    exclude:
    - 200*
    - 201*
    - 202006
  always: true

resources:
  repositories:
  - repository: buildimage
    type: github
    name: Azure/sonic-buildimage
    ref: master
    endpoint: build

pool: sonicbld

parameters:
- name: 'runId'
  type: string
  default: '0'

- name: 'branchName'
  type: string
  default: '202111'

stages:
- stage: UpgradeVersions
  jobs:
  - job: UpgradeVersions
    steps:
    - script: |
        if [ -z "$(which gh)" ]; then
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
        fi
      displayName: 'Install gh'
    - checkout: self
      displayName: 'Checkout code'
    - task: DownloadPipelineArtifact@2
      inputs:
        source: 'specific'
        project: 'build'
        runVersion: 'specific'
        runId: '${{ parameters.runId }}'
        patterns: '**/versions-*'
    - script: |
        mkdir -p target
        default_platform=broadcom
        artifacts=$(find $(Pipeline.Workspace) -maxdepth 1 -type d -name 'sonic-buildimage.*' | grep -v "sonic-buildimage.${default_platform}")
        echo "artifacts$artifacts"
        cp -r $(Pipeline.Workspace)/sonic-buildimage.${default_platform}/target/versions target/
        make freeze FREEZE_VERSION_OPTIONS=-r
        find files/build/versions 
        ordered_artifacts=$(echo "$artifacts" | grep -v -E "arm64|armhf" && echo "$artifacts" | grep -E "arm64|armhf")
        for artifact in $ordered_artifacts
        do
          rm -rf target/versions
          cp -r $artifact/target/versions target/
          OPTIONS="-a -d"
          [[ "$artifact" == *arm64* || "$artifact" == *armhf* ]] && OPTIONS="-d"
          make freeze FREEZE_VERSION_OPTIONS="$OPTIONS"
        done
        git diff files/build/versions
      displayName: 'Freeze Versions'
    - script: |
        if [ -z "$GIT_USER" ]; then
          echo "Skipped to send the pull request, GIT_USER not set."
          exit 0
        fi
        GIT_STATUS=$(git status  --porcelain files/build/versions)
        if [ -z "$GIT_STATUS" ]; then
          echo "Skipped to send the pull request, no version change in files/build/versions"
          exit 0
        fi
        if [ ! -d "$HOME" ]; then
          sudo mkdir -p $HOME
          sudo chown -R $(id -un):$(id -gn) $HOME
        fi
        SOURCE_BRANCH=${{ parameters.branchName }}
        REPO_NAME=$(Build.Repository.Name)
        [ -z "$GIT_REPO" ] && GIT_REPO=${REPO_NAME#*/}
        BRANCH_NAME=repd/versions/${SOURCE_BRANCH#refs/heads/}
        echo '#!/bin/bash' > git_env_password.sh
        echo 'echo $GIT_PASSWORD' >> git_env_password.sh
        chmod a+x git_env_password.sh
        export GIT_ASKPASS=./git_env_password.sh

        git config user.name $GIT_USER
        git config credential.https://github.com.username $GIT_USER
        git add files/build/versions
        git commit -m "[ci/build]: Upgrade SONiC package versions"
        git checkout -b $BRANCH_NAME
        git remote add remote https://github.com/$GIT_USER/$GIT_REPO
        git push remote HEAD:refs/heads/$BRANCH_NAME -f
        git branch -u remote/$BRANCH_NAME

      env:
        GIT_USER: $(GIT_USER)
        GIT_PASSWORD: $(GIT_PASSWORD)
      displayName: 'Send Pull Request'
    - publish: $(System.DefaultWorkingDirectory)/files/build/versions
      artifact: 'sonic-buildimage.versions'
      displayName: 'Archive SONiC versions'
    
